import { User, Task, LogEntry, Comment, ChecklistItem } from "./types";

function pad(n: number) {
  return String(n).padStart(2, "0");
}

function offsetDate(days: number): string {
  const d = new Date();
  d.setDate(d.getDate() + days);
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`;
}

function offsetDateTime(days: number, hh: number, mm: number): string {
  const d = new Date();
  d.setDate(d.getDate() + days);
  d.setHours(hh, mm, 0, 0);
  return d.toISOString();
}

function ci(
  id: string,
  label: string,
  progress: number,
  children: ChecklistItem[] = []
): ChecklistItem {
  return { id, label, progress, children };
}

export const USERS: User[] = [
  { id: "u1", name: "박관리", dept: "관리팀", isAdmin: true },
  { id: "u2", name: "이지원", dept: "관리팀", isAdmin: false },
  { id: "u3", name: "한서준", dept: "관리팀", isAdmin: false },
  { id: "u4", name: "오지훈", dept: "관리팀", isAdmin: false },
  { id: "u5", name: "서은채", dept: "관리팀", isAdmin: false },
  { id: "u6", name: "김재경", dept: "재경팀", isAdmin: true },
  { id: "u7", name: "정다은", dept: "재경팀", isAdmin: false },
  { id: "u8", name: "최수민", dept: "재경팀", isAdmin: false },
  { id: "u9", name: "노현우", dept: "재경팀", isAdmin: false },
  { id: "u10", name: "임소연", dept: "재경팀", isAdmin: false },
];

export const SEED_TASKS: Task[] = [
  {
    id: "t1",
    title: "부산센터 임차 계약 갱신 검토",
    description:
      "부산센터 임차 계약이 10월 말 만료 예정으로, 갱신 조건(임차료 인상률, 계약 기간) 검토 및 건물주 측과 협의 필요. 재경팀 예산안과 연계하여 1차 검토안 작성 요망.",
    dept: "관리팀",
    categoryLarge: "계약관리",
    categoryMedium: "임차계약",
    categorySmall: "갱신협상",
    assigneeId: "u1",
    center: "부산센터",
    priority: "높음",
    status: "대기",
    progress: 10,
    dueDate: offsetDate(-6),
    createdBy: "u1",
    createdAt: offsetDate(-16),
    checklist: [
      ci("ci_t1_1", "임차 조건 검토 (인상률·기간)", 60),
      ci("ci_t1_2", "건물주 협의", 40),
      ci("ci_t1_3", "계약서 날인", 0),
      ci("ci_t1_4", "재경팀 결재 상신", 0),
    ],
  },
  {
    id: "t2",
    title: "3분기 재고 실사 결과 취합",
    description: "전국 센터 3분기 재고 실사 결과를 취합하고 편차 원인을 분석한다.",
    dept: "관리팀",
    categoryLarge: "센터운영관리",
    categoryMedium: "실사/점검",
    categorySmall: "재고실사",
    assigneeId: "u2",
    center: "서울센터",
    priority: "보통",
    status: "진행중",
    progress: 60,
    dueDate: offsetDate(3),
    createdBy: "u2",
    createdAt: offsetDate(-16),
  },
  {
    id: "t3",
    title: "인천센터 설비 점검 보고서 작성",
    description: "인천센터 소방/전기 설비 정기 점검 결과 보고서 작성 및 결재 상신.",
    dept: "관리팀",
    categoryLarge: "시설/자산관리",
    categoryMedium: "설비점검",
    categorySmall: "소방안전점검",
    assigneeId: "u8",
    center: "인천센터",
    priority: "낮음",
    status: "완료",
    progress: 100,
    dueDate: offsetDate(-11),
    createdBy: "u8",
    createdAt: offsetDate(-29),
  },
  {
    id: "t4",
    title: "신규 입사자 좌석/장비 배치 계획",
    description: "9월 신규 입사자 2명 좌석 배치 및 노트북/사원증 준비.",
    dept: "관리팀",
    categoryLarge: "인사지원",
    categoryMedium: "근태/복지",
    categorySmall: "복지몰",
    assigneeId: "u3",
    center: "본사",
    priority: "보통",
    status: "검토중",
    progress: 80,
    dueDate: offsetDate(2),
    createdBy: "u3",
    createdAt: offsetDate(-14),
  },
  {
    id: "t5",
    title: "대구·광주센터 연간 예산안 취합",
    description: "대구센터, 광주센터 내년도 운영 예산안 취합 및 1차 검토.",
    dept: "관리팀",
    categoryLarge: "센터운영관리",
    categoryMedium: "예산취합",
    categorySmall: "센터별예산",
    assigneeId: "u7",
    center: "대구센터",
    priority: "높음",
    status: "진행중",
    progress: 35,
    dueDate: offsetDate(10),
    createdBy: "u7",
    createdAt: offsetDate(-8),
  },
  {
    id: "t6",
    title: "공문 발송대장 정리 및 보관",
    description: "8~9월 대내외 공문 발송대장 정리 및 문서고 보관.",
    dept: "관리팀",
    categoryLarge: "문서/공문관리",
    categoryMedium: "공문발송",
    categorySmall: "대내공문",
    assigneeId: "u2",
    center: "본사",
    priority: "낮음",
    status: "대기",
    progress: 0,
    dueDate: offsetDate(15),
    createdBy: "u2",
    createdAt: offsetDate(-2),
  },
  {
    id: "t7",
    title: "대전센터 소방/안전점검 대응",
    description: "대전센터 소방 특별점검 지적사항 조치 및 결과 보고.",
    dept: "관리팀",
    categoryLarge: "시설/자산관리",
    categoryMedium: "설비점검",
    categorySmall: "소방안전점검",
    assigneeId: "u1",
    center: "대전센터",
    priority: "높음",
    status: "진행중",
    progress: 50,
    dueDate: offsetDate(7),
    createdBy: "u1",
    createdAt: offsetDate(-5),
  },
  {
    id: "t8",
    title: "8월 법인카드 사용내역 정산",
    description: "관리팀·재경팀 법인카드 8월 사용내역 정산 및 증빙 확인.",
    dept: "재경팀",
    categoryLarge: "지출결의",
    categoryMedium: "경비집행",
    categorySmall: "법인카드",
    assigneeId: "u7",
    center: "본사",
    priority: "보통",
    status: "검토중",
    progress: 85,
    dueDate: offsetDate(5),
    createdBy: "u7",
    createdAt: offsetDate(-16),
  },
  {
    id: "t9",
    title: "3분기 부가세 신고 준비",
    description: "3분기 부가가치세 신고서 작성 및 증빙자료 취합.",
    dept: "재경팀",
    categoryLarge: "세무/신고",
    categoryMedium: "부가세",
    categorySmall: "신고서작성",
    assigneeId: "u6",
    center: "본사",
    priority: "높음",
    status: "진행중",
    progress: 40,
    dueDate: offsetDate(9),
    createdBy: "u6",
    createdAt: offsetDate(-6),
  },
  {
    id: "t10",
    title: "신규 거래처 계약조건 검토 (물류포장재)",
    description: "물류포장재 신규 공급업체 계약조건(단가, 결제조건) 검토.",
    dept: "재경팀",
    categoryLarge: "거래처관리",
    categoryMedium: "신규등록",
    categorySmall: "계약조건검토",
    assigneeId: "u9",
    center: "본사",
    priority: "보통",
    status: "대기",
    progress: 0,
    dueDate: offsetDate(-2),
    createdBy: "u9",
    createdAt: offsetDate(-3),
  },
  {
    id: "t11",
    title: "센터별 인건비 예산 조정",
    description: "하반기 센터별 인건비 예산 조정안 확정 및 배포.",
    dept: "재경팀",
    categoryLarge: "예산관리",
    categoryMedium: "추경/조정",
    categorySmall: "예산조정",
    assigneeId: "u8",
    center: "본사",
    priority: "낮음",
    status: "완료",
    progress: 100,
    dueDate: offsetDate(-20),
    createdBy: "u8",
    createdAt: offsetDate(-35),
  },
  {
    id: "t12",
    title: "센터 배송차량 접촉사고 처리 (서울센터 1호차)",
    description: "서울센터 배송차량이 골목 진입 중 접촉사고 발생. 사실관계 확인 후 수리·보험·비용 정산까지 진행.",
    dept: "관리팀",
    categoryLarge: "시설/자산관리",
    categoryMedium: "자산관리",
    categorySmall: "차량관리",
    assigneeId: "u4",
    center: "서울센터",
    priority: "높음",
    status: "진행중",
    progress: 30,
    dueDate: offsetDate(6),
    createdBy: "u4",
    createdAt: offsetDate(-3),
    checklist: [
      ci("ci_t12_1", "사고 사실 확인", 100),
      ci("ci_t12_2", "사고 수리 진행", 40),
      ci("ci_t12_3", "보험 접수 확인", 20, [
        ci("ci_t12_3_1", "보험사 서류 제출", 50),
        ci("ci_t12_3_2", "심사 결과 대기", 0),
      ]),
      ci("ci_t12_4", "비용 입금(환입) 확인", 0),
    ],
  },
];

export const SEED_LOG_ENTRIES: LogEntry[] = [
  {
    id: "l1",
    taskId: "t1",
    authorId: "u1",
    content: "업무 등록. 계약 만료일 확인 완료(10월 31일). 기존 계약서 첨부합니다.",
    attachments: ["부산센터_임차계약서_2023.pdf"],
    createdAt: offsetDateTime(-16, 9, 12),
  },
  {
    id: "l2",
    taskId: "t1",
    authorId: "u1",
    content: "건물주 측과 1차 통화 진행. 다음 주 중 미팅 일정 조율 중.",
    attachments: [],
    createdAt: offsetDateTime(-11, 10, 5),
  },
  {
    id: "l3",
    taskId: "t1",
    authorId: "u1",
    content: "건물주 미팅 완료. 임차료 인상률 4%로 잠정 합의. 계약서 초안 확인 부탁드립니다.",
    attachments: ["계약서_초안_v2.docx"],
    createdAt: offsetDateTime(-6, 14, 20),
  },
  {
    id: "l4",
    taskId: "t2",
    authorId: "u2",
    content: "업무 등록. 전국 12개 센터에 실사 양식 배포.",
    attachments: ["3분기_재고실사_양식.xlsx"],
    createdAt: offsetDateTime(-16, 9, 30),
  },
  {
    id: "l5",
    taskId: "t2",
    authorId: "u2",
    content: "9개 센터 회신 완료, 3개 센터 회신 대기 중.",
    attachments: [],
    createdAt: offsetDateTime(-4, 11, 0),
  },
  {
    id: "l6",
    taskId: "t8",
    authorId: "u7",
    content: "업무 등록. 8월 법인카드 명세서 다운로드 완료.",
    attachments: ["법인카드_명세서_8월.pdf"],
    createdAt: offsetDateTime(-16, 9, 0),
  },
  {
    id: "l7",
    taskId: "t8",
    authorId: "u7",
    content: "증빙 누락 3건 확인, 담당자에게 소명 요청함.",
    attachments: [],
    createdAt: offsetDateTime(-2, 13, 40),
  },
];

export const SEED_COMMENTS: Comment[] = [
  {
    id: "c1",
    targetType: "log",
    targetId: "l3",
    authorId: "u7",
    content: "인상률 4%면 예산안에 반영 가능할 것 같아요. 확정되면 알려주세요.",
    createdAt: offsetDateTime(-6, 15, 1),
  },
  {
    id: "c2",
    targetType: "log",
    targetId: "l3",
    authorId: "u6",
    content: "확정되면 바로 결재 올려주세요.",
    createdAt: offsetDateTime(-6, 16, 40),
  },
  {
    id: "c3",
    targetType: "log",
    targetId: "l1",
    authorId: "u6",
    content: "재경팀 예산안 초안 공유드립니다. 인상률 5% 이내로 협의 부탁드려요.",
    createdAt: offsetDateTime(-15, 9, 30),
  },
  {
    id: "c4",
    targetType: "checklist",
    targetId: "ci_t12_2",
    authorId: "u1",
    content: "정비소 견적 받았습니다. 부품 수급까지 3일 정도 걸린다고 하네요.",
    createdAt: offsetDateTime(-1, 11, 20),
  },
  {
    id: "c5",
    targetType: "checklist",
    targetId: "ci_t12_3",
    authorId: "u4",
    content: "보험사에 접수번호 받아서 서류 제출까지 완료했습니다.",
    createdAt: offsetDateTime(-1, 16, 5),
  },
];
